//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8784
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShouldPadMachine.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShouldPadMachine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ButtonOK_OFF {
            get {
                object obj = ResourceManager.GetObject("ButtonOK_OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ButtonOK_ON {
            get {
                object obj = ResourceManager.GetObject("ButtonOK_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CommunicationError {
            get {
                object obj = ResourceManager.GetObject("CommunicationError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CrdWarn {
            get {
                object obj = ResourceManager.GetObject("CrdWarn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DownSensorErr {
            get {
                object obj = ResourceManager.GetObject("DownSensorErr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DownSensorErrL {
            get {
                object obj = ResourceManager.GetObject("DownSensorErrL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img1d1 {
            get {
                object obj = ResourceManager.GetObject("img1d1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img1d2 {
            get {
                object obj = ResourceManager.GetObject("img1d2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img2d1 {
            get {
                object obj = ResourceManager.GetObject("img2d1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img2d2 {
            get {
                object obj = ResourceManager.GetObject("img2d2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img3d1 {
            get {
                object obj = ResourceManager.GetObject("img3d1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img3d2 {
            get {
                object obj = ResourceManager.GetObject("img3d2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img4d1 {
            get {
                object obj = ResourceManager.GetObject("img4d1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img4d2 {
            get {
                object obj = ResourceManager.GetObject("img4d2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img5d1 {
            get {
                object obj = ResourceManager.GetObject("img5d1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img5d2 {
            get {
                object obj = ResourceManager.GetObject("img5d2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img6d1 {
            get {
                object obj = ResourceManager.GetObject("img6d1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img6d2 {
            get {
                object obj = ResourceManager.GetObject("img6d2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img7d1 {
            get {
                object obj = ResourceManager.GetObject("img7d1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img7d2 {
            get {
                object obj = ResourceManager.GetObject("img7d2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img8d1 {
            get {
                object obj = ResourceManager.GetObject("img8d1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img8d2 {
            get {
                object obj = ResourceManager.GetObject("img8d2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img9d1 {
            get {
                object obj = ResourceManager.GetObject("img9d1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img9d2 {
            get {
                object obj = ResourceManager.GetObject("img9d2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgAct1 {
            get {
                object obj = ResourceManager.GetObject("imgAct1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgAct2 {
            get {
                object obj = ResourceManager.GetObject("imgAct2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgAddPoit1 {
            get {
                object obj = ResourceManager.GetObject("imgAddPoit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgAddPoit2 {
            get {
                object obj = ResourceManager.GetObject("imgAddPoit2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgAuto1 {
            get {
                object obj = ResourceManager.GetObject("imgAuto1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgAuto2 {
            get {
                object obj = ResourceManager.GetObject("imgAuto2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgBacktype1_1 {
            get {
                object obj = ResourceManager.GetObject("imgBacktype1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgBacktype1_2 {
            get {
                object obj = ResourceManager.GetObject("imgBacktype1_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgBlow1 {
            get {
                object obj = ResourceManager.GetObject("imgBlow1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgBlow2 {
            get {
                object obj = ResourceManager.GetObject("imgBlow2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgCarry1 {
            get {
                object obj = ResourceManager.GetObject("imgCarry1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgCarry2 {
            get {
                object obj = ResourceManager.GetObject("imgCarry2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgCatch1 {
            get {
                object obj = ResourceManager.GetObject("imgCatch1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgCatch2 {
            get {
                object obj = ResourceManager.GetObject("imgCatch2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgClamp1 {
            get {
                object obj = ResourceManager.GetObject("imgClamp1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgClamp2 {
            get {
                object obj = ResourceManager.GetObject("imgClamp2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgCopyAll1 {
            get {
                object obj = ResourceManager.GetObject("imgCopyAll1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgCopyAll2 {
            get {
                object obj = ResourceManager.GetObject("imgCopyAll2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgCopyCur1 {
            get {
                object obj = ResourceManager.GetObject("imgCopyCur1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgCopyCur2 {
            get {
                object obj = ResourceManager.GetObject("imgCopyCur2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgCut1 {
            get {
                object obj = ResourceManager.GetObject("imgCut1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgCut2 {
            get {
                object obj = ResourceManager.GetObject("imgCut2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgDelPoint1 {
            get {
                object obj = ResourceManager.GetObject("imgDelPoint1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgDelPoint2 {
            get {
                object obj = ResourceManager.GetObject("imgDelPoint2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgDrawAll1 {
            get {
                object obj = ResourceManager.GetObject("imgDrawAll1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgDrawAll2 {
            get {
                object obj = ResourceManager.GetObject("imgDrawAll2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgEdit1 {
            get {
                object obj = ResourceManager.GetObject("imgEdit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgEdit2 {
            get {
                object obj = ResourceManager.GetObject("imgEdit2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgEdit3 {
            get {
                object obj = ResourceManager.GetObject("imgEdit3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgEditLock1 {
            get {
                object obj = ResourceManager.GetObject("imgEditLock1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgEditLock2 {
            get {
                object obj = ResourceManager.GetObject("imgEditLock2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgExit1 {
            get {
                object obj = ResourceManager.GetObject("imgExit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgExit2 {
            get {
                object obj = ResourceManager.GetObject("imgExit2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgGetXml1 {
            get {
                object obj = ResourceManager.GetObject("imgGetXml1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgGetXml2 {
            get {
                object obj = ResourceManager.GetObject("imgGetXml2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgHalfLift1 {
            get {
                object obj = ResourceManager.GetObject("imgHalfLift1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgHalfLift2 {
            get {
                object obj = ResourceManager.GetObject("imgHalfLift2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgHalfRight1 {
            get {
                object obj = ResourceManager.GetObject("imgHalfRight1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgHalfRight2 {
            get {
                object obj = ResourceManager.GetObject("imgHalfRight2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgLift1 {
            get {
                object obj = ResourceManager.GetObject("imgLift1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgLift2 {
            get {
                object obj = ResourceManager.GetObject("imgLift2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgMenu1 {
            get {
                object obj = ResourceManager.GetObject("imgMenu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgMenu2 {
            get {
                object obj = ResourceManager.GetObject("imgMenu2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgMenu3 {
            get {
                object obj = ResourceManager.GetObject("imgMenu3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgMir1 {
            get {
                object obj = ResourceManager.GetObject("imgMir1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgMir2 {
            get {
                object obj = ResourceManager.GetObject("imgMir2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgMirror1 {
            get {
                object obj = ResourceManager.GetObject("imgMirror1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgMirror2 {
            get {
                object obj = ResourceManager.GetObject("imgMirror2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNext1 {
            get {
                object obj = ResourceManager.GetObject("imgNext1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNext2 {
            get {
                object obj = ResourceManager.GetObject("imgNext2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNor {
            get {
                object obj = ResourceManager.GetObject("imgNor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgNor1 {
            get {
                object obj = ResourceManager.GetObject("imgNor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgPointCh1 {
            get {
                object obj = ResourceManager.GetObject("imgPointCh1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgPointCh2 {
            get {
                object obj = ResourceManager.GetObject("imgPointCh2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgPre1 {
            get {
                object obj = ResourceManager.GetObject("imgPre1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgPre2 {
            get {
                object obj = ResourceManager.GetObject("imgPre2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgPress1 {
            get {
                object obj = ResourceManager.GetObject("imgPress1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgPress2 {
            get {
                object obj = ResourceManager.GetObject("imgPress2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgRepeal1 {
            get {
                object obj = ResourceManager.GetObject("imgRepeal1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgRepeal2 {
            get {
                object obj = ResourceManager.GetObject("imgRepeal2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgReturn1 {
            get {
                object obj = ResourceManager.GetObject("imgReturn1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgReturn2 {
            get {
                object obj = ResourceManager.GetObject("imgReturn2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgRight1 {
            get {
                object obj = ResourceManager.GetObject("imgRight1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgRight2 {
            get {
                object obj = ResourceManager.GetObject("imgRight2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSelAll1 {
            get {
                object obj = ResourceManager.GetObject("imgSelAll1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSelAll2 {
            get {
                object obj = ResourceManager.GetObject("imgSelAll2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSetParam1 {
            get {
                object obj = ResourceManager.GetObject("imgSetParam1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSetParam2 {
            get {
                object obj = ResourceManager.GetObject("imgSetParam2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSetPos1 {
            get {
                object obj = ResourceManager.GetObject("imgSetPos1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSetPos2 {
            get {
                object obj = ResourceManager.GetObject("imgSetPos2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSingle {
            get {
                object obj = ResourceManager.GetObject("imgSingle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSysRe1 {
            get {
                object obj = ResourceManager.GetObject("imgSysRe1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgSysRe2 {
            get {
                object obj = ResourceManager.GetObject("imgSysRe2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgTest1 {
            get {
                object obj = ResourceManager.GetObject("imgTest1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgTest2 {
            get {
                object obj = ResourceManager.GetObject("imgTest2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgUnlock1 {
            get {
                object obj = ResourceManager.GetObject("imgUnlock1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgUnlock2 {
            get {
                object obj = ResourceManager.GetObject("imgUnlock2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgUpbtl1 {
            get {
                object obj = ResourceManager.GetObject("imgUpbtl1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgUpbtl2 {
            get {
                object obj = ResourceManager.GetObject("imgUpbtl2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgUpEco1 {
            get {
                object obj = ResourceManager.GetObject("imgUpEco1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgUpEco2 {
            get {
                object obj = ResourceManager.GetObject("imgUpEco2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgUpSrc1 {
            get {
                object obj = ResourceManager.GetObject("imgUpSrc1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap imgUpSrc2 {
            get {
                object obj = ResourceManager.GetObject("imgUpSrc2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IOLVoltWarn {
            get {
                object obj = ResourceManager.GetObject("IOLVoltWarn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftSensorErr {
            get {
                object obj = ResourceManager.GetObject("LeftSensorErr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftSensorErrL {
            get {
                object obj = ResourceManager.GetObject("LeftSensorErrL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LineBreakWarn {
            get {
                object obj = ResourceManager.GetObject("LineBreakWarn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MidSensorErr {
            get {
                object obj = ResourceManager.GetObject("MidSensorErr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MidSensorErrL {
            get {
                object obj = ResourceManager.GetObject("MidSensorErrL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ModeSwitchWarn {
            get {
                object obj = ResourceManager.GetObject("ModeSwitchWarn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightSensorErr {
            get {
                object obj = ResourceManager.GetObject("RightSensorErr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightSensorErrL {
            get {
                object obj = ResourceManager.GetObject("RightSensorErrL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ServoSensorErr {
            get {
                object obj = ResourceManager.GetObject("ServoSensorErr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SF_NoEcdWarn {
            get {
                object obj = ResourceManager.GetObject("SF_NoEcdWarn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SF_NoMotorWarn {
            get {
                object obj = ResourceManager.GetObject("SF_NoMotorWarn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SF_OCurWarn {
            get {
                object obj = ResourceManager.GetObject("SF_OCurWarn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SF_OLoadWarn {
            get {
                object obj = ResourceManager.GetObject("SF_OLoadWarn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SF_QepErrWarn {
            get {
                object obj = ResourceManager.GetObject("SF_QepErrWarn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SFLVoltWarn {
            get {
                object obj = ResourceManager.GetObject("SFLVoltWarn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap STLVoltWarn {
            get {
                object obj = ResourceManager.GetObject("STLVoltWarn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SysInfo1 {
            get {
                object obj = ResourceManager.GetObject("SysInfo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SysInfo2 {
            get {
                object obj = ResourceManager.GetObject("SysInfo2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SysRePowerWarn {
            get {
                object obj = ResourceManager.GetObject("SysRePowerWarn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SysTimeOutWarn {
            get {
                object obj = ResourceManager.GetObject("SysTimeOutWarn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TotalWorkedNumberOverflowWarn {
            get {
                object obj = ResourceManager.GetObject("TotalWorkedNumberOverflowWarn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpdataSuccess {
            get {
                object obj = ResourceManager.GetObject("UpdataSuccess", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpperSensorErr {
            get {
                object obj = ResourceManager.GetObject("UpperSensorErr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpperSensorErrL {
            get {
                object obj = ResourceManager.GetObject("UpperSensorErrL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap warn_due {
            get {
                object obj = ResourceManager.GetObject("warn_due", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap warn_Upgrade {
            get {
                object obj = ResourceManager.GetObject("warn_Upgrade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WorkedNumberOverflowWarn {
            get {
                object obj = ResourceManager.GetObject("WorkedNumberOverflowWarn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap X_NoMotorWarn {
            get {
                object obj = ResourceManager.GetObject("X_NoMotorWarn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap X_OCurWarn {
            get {
                object obj = ResourceManager.GetObject("X_OCurWarn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap X_OLoadWarn {
            get {
                object obj = ResourceManager.GetObject("X_OLoadWarn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap X_QepErrWarn {
            get {
                object obj = ResourceManager.GetObject("X_QepErrWarn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap XSensorErr {
            get {
                object obj = ResourceManager.GetObject("XSensorErr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Y_NoMotorWarn {
            get {
                object obj = ResourceManager.GetObject("Y_NoMotorWarn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Y_OCurWarn {
            get {
                object obj = ResourceManager.GetObject("Y_OCurWarn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Y_OLoadWarn {
            get {
                object obj = ResourceManager.GetObject("Y_OLoadWarn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Y_QepErrWarn {
            get {
                object obj = ResourceManager.GetObject("Y_QepErrWarn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YSensorErr {
            get {
                object obj = ResourceManager.GetObject("YSensorErr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
